/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f103xb.h"
#include "init.h"

void control_buttons(void);

uint8_t left_button_push = 0;
uint8_t right_button_push = 0;
uint8_t middle_button_push = 0;
uint8_t goasting_ms_counter_1 = 0;
uint8_t goasting_ms_counter_2 = 0;
uint8_t goasting_ms_counter_3 = 0;
uint8_t turn_left = 0;
uint8_t turn_right = 0;
uint16_t delay_cnt = 0;
uint8_t flash_cnt = 0;

void TIM1_UP_IRQHandler (void)
{
	TIM1->SR = 0;

	if (goasting_ms_counter_1 > 0 && goasting_ms_counter_1 < 100) goasting_ms_counter_1++;
	if (goasting_ms_counter_2 > 0 && goasting_ms_counter_2 < 100) goasting_ms_counter_2++;
	if (goasting_ms_counter_3 > 0 && goasting_ms_counter_3 < 100) goasting_ms_counter_3++;

	if (turn_left && flash_cnt < 20)
	{
		delay_cnt++;
		if (delay_cnt >= 200)
		{
			LEFT_LIGHT_SWITCH;
			delay_cnt = 0;
			flash_cnt++;
		}
		RIGHT_LIGHT_RESET;
	}
	else if (turn_right && flash_cnt < 20)
	{
		delay_cnt++;
		if (delay_cnt >= 200)
		{
			RIGHT_LIGHT_SWITCH;
			delay_cnt = 0;
			flash_cnt++;
		}
		LEFT_LIGHT_RESET;
	}
	else
	{
		turn_left = turn_right = 0;
		delay_cnt = 0;
		flash_cnt = 0;
		LEFT_LIGHT_RESET;
		RIGHT_LIGHT_RESET;
	}
}

int main(void)
{
    init_mcu();
    while (1)
    {
    	control_buttons();
    }
}

void control_buttons(void)
{
	uint8_t button_state = 0;
	uint8_t* ag_counter_ptr;
	uint8_t* button_flag;

	for (int i = 0; i < 3; i++)
	{
		switch (i)
		{
			case 0:
				button_state = LEFT_PUSH;
				ag_counter_ptr = &goasting_ms_counter_1;
				button_flag = &left_button_push;
				break;
			case 1:
				button_state = MIDDLE_PUSH;
				ag_counter_ptr = &goasting_ms_counter_2;
				button_flag = &middle_button_push;
				break;
			case 2:
				button_state = RIGHT_PUSH;
				ag_counter_ptr = &goasting_ms_counter_3;
				button_flag = &right_button_push;
				break;
			default:
				break;
		}

		if (*button_flag == 0 && button_state)
		{
			if (*ag_counter_ptr == 0)
			{
				*ag_counter_ptr = 1;
			}

			if (*ag_counter_ptr > 30 && button_state)
			{
				*ag_counter_ptr = 0;
				*button_flag = 1;

				switch (i)
				{
					case 0:
						turn_left ^= 1;
						turn_right = 0;
						flash_cnt = 0;
						break;
					case 1:
						MIDDLE_LIGHT_SWITCH;
						break;
					case 2:
						turn_right ^= 1;
						turn_left = 0;
						flash_cnt = 0;
						break;
					default:
						break;
				}
			}
		}
		else if (*button_flag == 0 && !button_state)
		{
			if (*ag_counter_ptr > 0) *ag_counter_ptr = 0;
		}

		else if (*button_flag == 1 && !button_state)
		{
			*ag_counter_ptr = 0;
			*button_flag = 0;
		}
	}
}
